@urlDefault=http://rafaelwilliam.com.br:5000

# @name getToken
POST {{urlDefault}}/login
Content-Type: application/json

{
    "userName": "string",
    "password": "string"
}

###
@token={{getToken.response.body}}

###
GET {{urlDefault}}/user
Content-Type: application/json
Authorization: Bearer {{token}}